# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1a82ebeaffa35c6098368013ad318551eee73abb18f5a16a7b4d71a894fc40fe0db4b9a13edf06573e2b3e0d57501ab5bd157b13b7b2a309212d827301a9f6d

test:
  secret_key_base: 74c1ae3292f2d6001d4bb6cd9d133f19e848f38bfc2c154ed458d296438613d9f715576ad92ebeb5a4ae3a7269101c408a3391856b254b26ba98277959dba462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
